name: Set up the repository
on:
  push:
    branches: [main]
jobs:
  cleanup:
    name: Set up the repository
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'airdrop-template'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Replace templates
        run: |
          shopt -s dotglob

          export LC_CTYPE=C
          export LANG=C

          # Project name is lowercase repository name (used in configs)
          REPO_NAME="${GITHUB_REPOSITORY,,}" # Of the form owner/repo
          REPO_NAME="${REPO_NAME##*/}" # Just the repo name

          # Extract EXTERNAL_SYSTEM from the project name
          # Expected format: airdrop-{system}-snap-in where {system} can be multiple words with dashes
          EXTERNAL_SYSTEM="TODO"
          if [[ "$REPO_NAME" =~ ^airdrop-(.+)-snap-in$ ]]; then
            EXTERNAL_SYSTEM="${BASH_REMATCH[1]}"
          fi

          # Create pretty version of external system name with proper capitalization
          PRETTY_EXTERNAL_SYSTEM="$(echo "$EXTERNAL_SYSTEM" | sed 's/-/ /g; s/\b\(.\)/\u\1/g')"
          ESCAPED_PRETTY_EXTERNAL_SYSTEM="$(echo "$PRETTY_EXTERNAL_SYSTEM" | sed 's/ /\\ /g')"

          echo "Project name: '$REPO_NAME'"
          echo "External system name: '$EXTERNAL_SYSTEM'"
          echo "Pretty external system name: '$PRETTY_EXTERNAL_SYSTEM'"

          echo "Replacing project name: <<REPO_NAME>> -> '$REPO_NAME'"
          find .github/templates -type f -exec sed -i "s/<<REPO_NAME>>/$REPO_NAME/g" {} \;

          echo "Replacing external system name: <<EXTERNAL_SYSTEM>> -> '$EXTERNAL_SYSTEM'"
          find .github/templates -type f -exec sed -i "s/<<EXTERNAL_SYSTEM>>/$EXTERNAL_SYSTEM/g" {} \;

          echo "Replacing pretty external system name: <<PRETTY_EXTERNAL_SYSTEM>> -> '$PRETTY_EXTERNAL_SYSTEM'"
          find .github/templates -type f -exec sed -i "s/<<PRETTY_EXTERNAL_SYSTEM>>/$ESCAPED_PRETTY_EXTERNAL_SYSTEM/g" {} \;

          echo "Moving template files to the root of the repository"
          rm -rf manifest.yaml README.md
          mv -f .github/templates/* .
          mv .github/dependabot.yml .
          rm -rf .github
          mkdir .github
          mv dependabot.yml .github/
          cp .cursor/mcp.json .mcp.json

          # Create CLAUDE.md from initial-mapping.mdc, removing the header
          sed '1,/^---$/d' initial-mapping.mdc | sed '1,/^$/d' > CLAUDE.md

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit --amend --no-edit

      - name: Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
