version: "2"

name: %PRETTY_NAME%
description: %PRETTY_NAME%

service_account:
  display_name: %PRETTY_NAME% Bot

developer_keyrings:
  - name: github_access_token
    description: GitHub access token
    display_name: GitHub Access Token

build_config:
  environment_variables:
    - name: GITHUB_ACCESS_TOKEN
      description: Token to access GitHub packages
      type: keyring
      value: github_access_token

functions:
  - name: extraction
    description: Extraction function for %PRETTY_NAME%
  - name: install_initial_domain_mapping
    description: Create blueprint and install initial domain mapping

keyring_types:
  - id: example-connection
    name: Example Connection
    description: Example Connection
    kind: "Secret"
    is_subdomain: true
    secret_config:
      secret_transform: ".token" # a JQ query
      fields:
        - id: token
          name: Token
          description: Example API token
      token_verification:
        urL: https://app.devrev.ai/favicon.ico
        method: GET

imports:
  - slug: %PROJECT_NAME%
    display_name: %PRETTY_NAME%
    description: %PRETTY_NAME%
    extractor_function: extraction
    allowed_connection_types:
      - example-connection

hooks:
  - type: activate
    function: install_initial_domain_mapping
